- frontend/.prettierrc
- frontend/locale/_build/src/Home.js.json
- frontend/locale/_build/src/report_screen.js.json
- frontend/locale/en/messages.js
- frontend/locale/en/messages.json
- frontend/locale/fr/messages.js
- frontend/locale/fr/messages.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/Home.js
- frontend/src/__tests__/report_screen_test.js
- frontend/src/report_screen.js
Just a form that asks "what happened"
uses `govuk-react`
> init report screen

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/LanguageSwitcher.js
- frontend/src/__tests__/LanguageSwitcher.test.js
- frontend/src/server.js
- frontend/src/utils/createApolloClient.js
- frontend/src/utils/createTestClient.js
Add language switching component based on Apollo-link-state.
> WIP: Add language switching component

- api/index.js
Server is not the default export anymore.
> Fix server import

- api/manifests/base/cybercrime-api-ingress.yaml
- api/manifests/base/kustomization.yaml
- api/manifests/overlays/gke/cybercrime-api-service.yaml
- api/manifests/overlays/gke/kustomization.yaml
- frontend/manifests/base/cybercrime-frontend-ingress.yaml
- frontend/manifests/base/kustomization.yaml
- frontend/manifests/overlays/gke/cybercrime-frontend-service.yaml
- frontend/manifests/overlays/gke/kustomization.yaml
- ingress/manifests/base/kustomization.yaml
- ingress/manifests/base/traefik-ingress-controller-cluster-role-binding.yaml
- ingress/manifests/base/traefik-ingress-controller-cluster-role.yaml
- ingress/manifests/base/traefik-ingress-controller-deployment.yaml
- ingress/manifests/base/traefik-ingress-controller-service-account.yaml
- ingress/manifests/overlays/gke/certs-claim.yaml
- ingress/manifests/overlays/gke/kustomization.yaml
- ingress/manifests/overlays/gke/traefik-ingress-controller-deployment.yaml
- ingress/manifests/overlays/gke/traefik-ingress-service.yaml
- ingress/manifests/overlays/minikube/kustomization.yaml
- ingress/manifests/overlays/minikube/traefik-ingress-service.yaml
This commit gets everything going in GKE and as part of the testing process also adds the remaining pieces to have everything run in Minikube. All the basics are working now.
> Add gke overlay

- frontend/package-lock.json
- frontend/package.json
Some of our dev dependencies ended up as regular dependencies.
> Reshuffle deps

- ingress/README.md
- ingress/manifests/overlays/gke/traefik-ingress-service.yaml
I nuked the cluster and rebuilt it under a new project and in doing so ended up with a new IP. Updating!
> Update the ingress service with our new IP

- frontend/package-lock.json
- frontend/package.json
- frontend/src/server.js
This feels... too easy... but here we go.
> Add SSRing Emotion

- frontend/manifests/base/cybercrime-frontend-deployment.yaml
- frontend/src/server.js
This PR adds liveness & ready checks to the front end container.
> Add liveness & ready check probes

- frontend/src/Screen2.js
This PR stacks up the form elements nicely.
> Stack some form elements

- frontend/locale/_build/src/Screen1.js.json
- frontend/locale/_build/src/Screen2.js.json
- frontend/locale/_build/src/thanks.js.json
- frontend/locale/en/messages.js
- frontend/locale/en/messages.json
- frontend/locale/fr/messages.js
- frontend/locale/fr/messages.json
- frontend/src/Screen1.js
> tweak text and add more French

- frontend/Dockerfile
- frontend/locale/_build/src/LandingPage.js.json
- frontend/locale/_build/src/Screen1.js.json
- frontend/locale/_build/src/thanks.js.json
- frontend/locale/en/messages.js
- frontend/locale/en/messages.json
- frontend/locale/fr/messages.js
- frontend/locale/fr/messages.json
- frontend/package-lock.json
- frontend/src/LandingPage.js
- frontend/src/Screen1.js
- frontend/src/thanks.js
This commit adds translations for missing phrases and also adds a `lingui
compile` step to the Dockerfile so newly added translations are sure to be
included in the production builds.
> Fix up French translations & include in build

- api/src/schema.js
- frontend/src/Screen1.js
- frontend/src/Screen2.js
- frontend/src/Screen3.js
- frontend/src/utils/createApolloClient.js
Add an "Other" box to the checkbox form, as per @samsadasivan 's suggestion
> Add a text box to screen 2

- frontend/locale/_build/src/Home.js.json
- frontend/locale/_build/src/LandingPage.js.json
- frontend/locale/_build/src/thanks.js.json
- frontend/locale/en/messages.js
- frontend/locale/en/messages.json
- frontend/locale/fr/messages.js
- frontend/locale/fr/messages.json
- frontend/src/__tests__/Thanks.test.js
- frontend/src/thanks.js
- frontend/src/utils/createApolloClient.js
> add counter to thanks screen

- ingress/manifests/overlays/gke/traefik-ingress-controller-deployment.yaml
[https://racontez-nous.cds-snc.ca/](https://racontez-nous.cds-snc.ca/)
[https://tell-us.cds-snc.ca/](https://tell-us.cds-snc.ca/)
> Change domains to tell-us and racontez-nous

- frontend/locale/_build/src/Screen2.js.json
- frontend/locale/en/messages.js
- frontend/locale/en/messages.json
- frontend/locale/fr/messages.js
- frontend/locale/fr/messages.json
- frontend/src/Screen2.js
on form 2, per Zak's suggestion.
> language tweak

- frontend/assets/theme.css
- frontend/src/App.js
> remove whitespace around header and footer

- frontend/assets/theme.css
- frontend/src/App.js
- frontend/src/Home.js
- frontend/src/server.js
fix SSR for location and global styling (ie global font and body margin)
> Router ssr

- frontend/src/App.js
- frontend/src/LandingPage.js
- frontend/src/LanguageSwitcher.js
- frontend/src/Screen3.js
- frontend/src/thanks.js
- frontend/src/utils/queriesAndMutations.js
> move queries to one file

- api/src/Report.js
- api/src/schema.js
> Move Report type to it's own file.

- docker-compose.yml
Search rankings! Geojson support! ++awesome!
> Update to ArangoDB 3.4

- frontend/jest.setup.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/Screen1.js
- frontend/src/WhatHappenedForm.js
- frontend/src/__tests__/Screen1.test.js
- frontend/src/__tests__/WhatHappenedForm.test.js
This commit got bigger than anticipated, but the idea here is splitting Screen1 into some smaller pieces.
> Split WhatHappenedForm out of Screen1

- api/package-lock.json
- api/package.json
> Update API dependencies

- ingress/manifests/traefik-ingress-controller-deployment.yaml
As it says on the tin. This enables gzip compression for ports 80 and 443
> Enable gzip compression

- ingress/manifests/traefik-ingress-controller-deployment.yaml
Adding annotation so that it's picked up by Flux.
> Automate ingress controller deployment

- frontend/manifests/kustomization.yaml
- ingress/manifests/kustomization.yaml
These files were left dangling after the removal of kustomize.
> Remove kustomize remnants

- api/manifests/cybercrime-api-ingress.yaml
- frontend/manifests/cybercrime-frontend-ingress.yaml
> Set X-Frame-options header

- api/manifests/cybercrime-api-ingress.yaml
- frontend/manifests/cybercrime-frontend-ingress.yaml
> Add X-XSS-Protection header

- frontend/src/Screen2.js
> fix flaky breadcrumb

- frontend/locale/_build/src/App.js.json
- frontend/locale/_build/src/Home.js.json
- frontend/locale/_build/src/LandingPage.js.json
- frontend/locale/_build/src/Screen1.js.json
- frontend/locale/_build/src/Screen2.js.json
- frontend/locale/_build/src/Screen3.js.json
- frontend/locale/_build/src/Stats.js.json
- frontend/locale/_build/src/WhatHappenedForm.js.json
- frontend/locale/_build/src/thanks.js.json
- frontend/locale/en/messages.js
- frontend/locale/en/messages.json
- frontend/locale/fr/messages.js
- frontend/locale/fr/messages.json
- frontend/package-lock.json
- frontend/src/Screen2.js
- frontend/src/Screen3.js
- frontend/src/WhatHappenedForm.js
- frontend/src/__tests__/WhatHappenedForm.test.js
fixes #64 - instead of disabling "submit" buttons for no input, show an error message if user clicks them.
> Error messages

- compliance/api-deployment.yaml
- compliance/api-service.yaml
- compliance/api-virtualservice.yaml
- compliance/checks-claim.yaml
- compliance/checks/sa_11_1.yaml
- compliance/cluster-role-binding.yaml
- compliance/cluster-role.yaml
- compliance/github-virtualservice.yaml
- compliance/mongo-claim.yaml
- compliance/mongo-deployment.yaml
- compliance/mongo-service.yaml
- compliance/namespace.yaml
- compliance/watcher-deployment.yaml
- compliance/watcher-service.yaml
- ingress/manifests/cluster-admin-clusterrolebinding.yaml
So what did I do here:
1. Added a `label` to the most under-utilized node in the K8s cluster. `comliance: master`. I chose master because I initially used `compliance: true` and k8s threw up on me. So the Stack overflow example had something with `master` so I chose `master`. All compliance stuff needs to run there because they share a claim and claims can not be across nodes.
2. Gave my cds-snc user elevated permissions in the cluster. I had to do this to create an user in the `symmorfosi` namespace because it needs to be able to reschedule jobs. I just tagged myself into the cluster admin rolebinding that mike has set up.
3. I created deployments and services for the following:
- Compliance Watcher: this restarts jobs in the `symmorfosi` namespace. 
- Compliance API: this ingresses JSON …
> Compliance API

- frontend/src/TrackPageViews.js
> Anonymize ip addresses for Google analytics

- api/index.js
- api/package-lock.json
- api/package.json
- frontend/package-lock.json
- frontend/package.json
- frontend/public/service-worker.js
- frontend/src/index.js
- frontend/src/server.js
Use `@cdssnc/logdriver` for logging
> replace console.log with Logger

- compliance/checks/cds_li_1.yaml
A compliance API check for lighthouse scores:
https://tell-us-compliance.herokuapp.com/controls/CDS-LI-1
> Added lighthouse check for compliance

- compliance/checks-claim.yaml
- compliance/checks/sa_11_4.yaml
- compliance/mongo-claim.yaml
Seems like you follow good review practices:
> Git PR review check

- frontend/src/App.js
- frontend/src/server.js
Local dummy puts link to load google font in App.js instead of server.js, causing fonts to flicker on load.  This PR fixes the issue
> Fix google font load issue

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/LandingPage.js
- frontend/src/__tests__/Header.test.js
- frontend/src/components/header/index.js
- frontend/src/components/header/presets.js
- frontend/src/server.js
- frontend/src/theme/index.js
Sorry for the size of this PR! It:
- Adds in all the dependencies for the new components
- Adds in the base theme file
- Wraps the content of App.js in the Emotion ThemeProvider component
- Readds Emotion SSR because as it turns out emotion-themeing doesn't support SSR out of the box quite yet ( :( )
- Adds the Header component to prove everything works!
> Add theme & header component

- frontend/src/Stats.js
- frontend/src/theme/index.js
- frontend/src/withLanguageSwitching.js
use new `<P>` instead of `<p>`
> Use new paragraph component

- frontend/package-lock.json
- frontend/package.json
upgraded a bunch of packages in `frontend`. Remaining is `jest` and `babel-jest`, which have major upgrades that broke things.
> Upgrade packages

- frontend/src/index.js
- package-lock.json
> poke compliance api

- frontend/locale/en/messages.json
- frontend/locale/fr/messages.json
- frontend/manifests/cybercrime-frontend-deployment.yaml
- frontend/package-lock.json
- frontend/src/Screen2.js
- frontend/src/__tests__/Breadcrumb.test.js
- frontend/src/components/breadcrumb/index.js
- frontend/src/components/breadcrumb/presets.js
- frontend/src/components/text/presets.js
make a breadcrumb component
Example on the second form (How did that Happen?)
> Breadcrumbs

- frontend/src/components/header/__tests__/Header.test.js
- frontend/src/components/link/__tests__/Link.test.js
- frontend/src/components/list-item/__tests__/ListItem.test.js
- frontend/src/components/ordered-list/__tests__/OrderedList.test.js
- frontend/src/components/paragraph/__tests__/Paragraph.test.js
- frontend/src/components/text/__tests__/Text.test.js
- frontend/src/components/unordered-list/__tests__/UnorderedList.test.js
What it says on the tin - move the tests over to the individual test folders & update the imports. Makes the tests easier to find and less work if/when we export the components out later.
> Move tests to individual test folders

- frontend/src/components/button/index.js
- frontend/src/theme/index.js
> refactor colors in theme and add button colorStyle

- frontend/locale/en/messages.json
- frontend/locale/fr/messages.json
- frontend/src/Home.js
- frontend/src/PageNotFound.js
> add simple 404 page

- frontend/src/__tests__/Screen2.test.js
some crazy merge problems. We need to add the slack notification.
> fix failing master

- frontend/src/__tests__/Screen1.test.js
> break master to test the cloud function / Slack web hook

- frontend/src/__tests__/Screen1.test.js
Reverts cds-snc/report-a-cybercrime#175
> Revert "break master to test the cloud function / Slack web hook"

- frontend/cloudbuild.yaml
- frontend/locale/en/messages.json
- frontend/locale/fr/messages.json
- frontend/package.json
- frontend/utils/checkTranslations.js
resolves #167 
Note that the test fails below due to a missing translation. Adding the translation fixes the test.
> Make sure we're not missing any translations

- frontend/package-lock.json
- frontend/package.json
This package isn't used in our application but had somehow found it's way into
our package.json.
> Remove react-markdown

- frontend/src/WhatHappenedForm.js
- frontend/src/components/text-area/__tests__/TextArea.test.js
- frontend/src/components/text-area/index.js
- frontend/src/theme/index.js
> TextArea component

- frontend/src/components/input/__tests__/Input.test.js
- frontend/src/components/input/index.js
This PR adds a basic input component with styled system to be used to build up other form components.
> Add input component

- frontend/src/Home.js
- frontend/src/Screen1.js
- frontend/src/Screen2.js
- frontend/src/Screen3.js
- frontend/src/Stats.js
move all the discovery tool pages to /old/... We had moved just the old landing page, but that broke many of the links.
> fix paths to old app

- api/package-lock.json
- api/package.json
> Update API deps

- .github/main.workflow
- api/Dockerfile
- frontend/Dockerfile
Let us take this linter for a spin
> Added dockerfile linter

- api/src/__tests__/mutations.test.js
Dates are different every day it turns out.
> Remove date from test

- api/manifests/cybercrime-api-deployment.yaml
- frontend/manifests/cybercrime-frontend-deployment.yaml
This commit updates the containers to use the proper image registry for the
current project.
> Update container registry

- api/manifests/cybercrime-api-deployment.yaml
- frontend/manifests/cybercrime-frontend-deployment.yaml
> Fix registry name

- frontend/src/Home.js
- frontend/src/Page1.js
- frontend/src/Summary.js
- frontend/src/__tests__/Home.test.js
Page1 is now mounted at /
Summary is now at /summary
Page1 continue > /summary
> Remove unneeded routes

- frontend/src/Stats.js
:chart_with_downwards_trend: :crying_cat_face:
> Make chart grey

- api/src/__tests__/PhoneNumber.test.js
- api/src/types/PhoneNumber.js
A field whose value conforms to the standard E.164 format as specified in: https://en.wikipedia.org/wiki/E.164. 
I figure we can change as we see fit.
I should add that I created a mutation and successfully tested inserting with this type.
> First iteration of phone type

- frontend/src/LanguageSwitcher.js
- frontend/src/__tests__/LanguageSwitcher.test.js
- frontend/src/components/button-link/__tests__/ButtonLink.test.js
- frontend/src/components/button-link/index.js
we just had "inherit" for the font, which was giving us the default font.
> use theme font in language switcher button

- api/src/FlaggingSummary.js
- api/src/Stats.js
- api/src/__tests__/mutations.test.js
- api/src/__tests__/server.test.js
- api/src/schema.js
- frontend/src/Page2.js
- frontend/src/Stats.js
- frontend/src/__tests__/Stats.test.js
- frontend/src/utils/queriesAndMutations.js
change api and frontend to add the page 2 identifier to the database (via GraphQL)
> hookup page2

- api/bin/print-schema
- api/package-lock.json
- api/package.json
- api/schema.graphql
This commit adds a script that prints the current schema and a git hook that
includes the generated schema file in commits when it changes.
The idea is to make schema changes more visible and understandable and pave the
way for the automating the detection of breaking schema changes.
> Include schema in commits that change it.

- api/package-lock.json
> Update jsyaml to fix vulnerabilities

- api/manifests/cybercrime-api-deployment.yaml
- frontend/manifests/cybercrime-frontend-deployment.yaml
Stop deploying all the things.
> Fix flux annotations

- frontend/src/Page2.js
Noticed an issue on page 2 on my ipad (that we're testing with tomorrow):
This is a quick hack to change to
> shrink page 2 for test :(

- frontend/package-lock.json
- frontend/package.json
This version actually has fewer vulnerabilities than the more recent alpha2
version.
> Pin razzle version to 3 alpha0

- README.md
Took a stab at updating the readme with some instructions for running the entire project via Docker. I've tried to be as thorough with the steps as possible. Feedback please!
> Update readme with Docker instructions

- api/src/__tests__/PhoneNumber.test.js
- api/src/__tests__/URL.test.js
This stops eslint from yelling
> Remove unused global vars

- frontend/src/Home.js
- frontend/src/Page2.js
- frontend/src/Summary.js
This is the first step away from the hardcoded values we are using for demo purposes.
> Put the identifier in the URL bar

- api/schema.graphql
- frontend/src/Summary.js
From `‘` to `’` (correct orientation)
> Fix apostrophe on summary page

- frontend/src/utils/queriesAndMutations.js
> Remove unused graphql queries

- api/.prettierignore
continuing #275 
probably want this here as well.
> don't prettier schema.graphql in api as well

- frontend/locale/en/messages.json
- frontend/locale/fr/messages.json
- frontend/src/Option2Page.js
> cleanup option 2 page

- frontend/package-lock.json
- frontend/src/Option1Page.js
- frontend/src/Option2Page.js
- frontend/src/Option3Page.js
- frontend/src/components/paragraph/index.js
Changed the content to be centre aligned on all the option pages.
> Content change to align the text on the option pages.

- frontend/locale/en/messages.json
- frontend/locale/fr/messages.json
- frontend/src/Option2Page.js
> Remove CAFC info

- README.md
otherwise `make dev` won't work.
> add module install instructions to README

- api/cloudbuild.yaml
- api/package.json
- frontend/cloudbuild.yaml
- frontend/package.json
use `jest --coverage` essentially. Requirements set at 50% for now.
> Add code coverage test

- frontend/src/__tests__/FileUpload.test.js
- frontend/src/components/radio-button/__tests__/RadioButton.test.js
#331 didn't include a few tests that had been added after #331 branched from master.
> use new react testing library

- frontend/package-lock.json
- frontend/src/ContactInfoPage.js
- frontend/src/FileUploadPage.js
- frontend/src/MoneyLostPage.js
- frontend/src/ScamInfoPage.js
- frontend/src/SuspectInfoPage.js
- frontend/src/ThankYou.js
- frontend/src/forms/ContactInfoForm.js
- frontend/src/forms/MoneyLostForm.js
- frontend/src/forms/ScamInfoForm.js
- frontend/src/forms/SuspectInfoForm.js
- frontend/src/forms/__tests__/MoneyLostForm.test.js
- frontend/src/forms/__tests__/ScamInfoForm.test.js
- frontend/utils/checkTranslations.js
These are the changes that I made to the: 
- ScamInfopage
- Suspectinfo
- MoneyLost 
- ContactInfo
- Thankyou
// None of the question pages
// No French
> content changes to all the form pages and the last page

- frontend/src/FilesToUpload.js
- frontend/src/Suspectinfo.js
- frontend/src/Willbecontacted.js
> put all yes/no buttons in rows rather than cols

- frontend/src/ConfirmationPage.js
- frontend/src/forms/SuspectInfoForm.js
> fix suspect info language

- frontend/src/FileUploadPage.js
partially addresses #396 
* move attach file button up a bit
* hline above the "0 files attached" line
to
> tweak file upload page

- frontend/src/ConfirmationPage.js
link last page "cancel report" button to landing page
> link last page "cancel report" button to landing page

- frontend/src/FileUploadPage.js
- frontend/src/forms/ContactInfoForm.js
- frontend/src/forms/MoneyLostForm.js
- frontend/src/forms/ScamInfoForm.js
- frontend/src/forms/SuspectInfoForm.js
resolves #402 
make all  "cancel report" button lead  to landing page.
> make all  "cancel report" button lead  to landing page

- api/schema.graphql
- frontend/locale/en/messages.json
- frontend/locale/fr/messages.json
- frontend/src/FileUploadPage.js
- frontend/src/__tests__/FileUploadPage.test.js
- frontend/src/__tests__/Stats.test.js
resolves #422 
use lingui to translate plurals appropriately.
> pluralize file(s) appropriately

- frontend/src/components/stepper/_tests_/Stepper.test.js
together with #444 this fixes #412
> fix stepper test

- frontend/src/ConfirmationPage.js
- frontend/src/ContactInfoPage.js
- frontend/src/FileUploadPage.js
- frontend/src/FilesToUpload.js
- frontend/src/LandingPage.js
- frontend/src/LoseMoney.js
- frontend/src/MoneyLostPage.js
- frontend/src/ScamInfoPage.js
- frontend/src/SuspectInfoPage.js
- frontend/src/Suspectinfo.js
- frontend/src/ThankYou.js
- frontend/src/Willbecontacted.js
fixed a couple errors that were being thrown to console when the landing page or thanks page loaded. Also switched some html tags to our versions. Finally, changed some css to styled-system props.
> Minor clean up

- frontend/.eslintrc.json
> Allow unused vars when prefixed with _

- frontend/src/ClientResolvers.js
- frontend/src/server.js
> fix linting in master

- frontend/package-lock.json
`fixed 13026 of 13090 vulnerabilities in 904403 scanned packages`
:open_mouth:
> Update vulnerable dependencies

- api/package-lock.json
`npm audit fix` run in api 
```
09:58 $ npm audit fix
removed 2 packages and updated 4 packages in 12.698s
fixed 15480 of 15480 vulnerabilities in 862305 scanned packages
```
> fix api vulnerabilities

- frontend/src/components/topbanner/index.js
> keep top banner same height on mobile

- frontend/utils/loadTesting.js
load test our https://www.report-a-cybercrime.alpha.rcmp-grc.gc.ca/ page
> add "load testing" function

- api/utils/loadTesting.js
resolves #483 
add a script to load test the api (by querying for the reportCount).
> k6 script for load testing graphql api

- README.md
- api/utils/loadTesting.js
- frontend/utils/loadTesting.js
tweaked scripts a bit and added docs
> Load testing docs

- frontend/public/googled96ce8847a7c181c.html
- frontend/public/robots.txt
so we can view Google SEO data via https://search.google.com/search-console
Also change `robots.txt` file to block web crawlers from indexing the site.
> add a file to allow access to google search view

- frontend/src/ConfirmationPage.js
- frontend/src/ContactInfoPage.js
- frontend/src/FileUploadPage.js
- frontend/src/FileUploadYesNoPage.js
- frontend/src/MoneyLostPage.js
- frontend/src/MoneyLostYesNoPage.js
- frontend/src/SuspectInfoPage.js
- frontend/src/SuspectInfoYesNoPage.js
- frontend/src/WillBeContactedYesNoPage.js
remove links in stepper bar. make the stepper numbers are not clickable
> remove links in stepper bar. make the stepper numbers are not clickable

- frontend/src/App.js
- frontend/src/components/topbanner/index.js
- frontend/src/components/warning-banner/index.js
`TopBanner` and `WarningBanner` both had their own `<header>` tags.  This was causing Axe to throw a warning. Here I moved the `<header>` tag up to `App` and put both `TopBanner` and `WarningBanner` inside it.
> Move header tag to App.js

- frontend/src/forms/ContactInfoForm.js
- frontend/src/forms/MoneyLostForm.js
- frontend/src/forms/ScamInfoForm.js
- frontend/src/forms/SuspectInfoForm.js
This will allow screenreaders to know what group the radio buttons or checkboxes belong to.
> use fieldsets around radio buttons and checkboxes

- api/schema.graphql
- api/src/schema.js
- frontend/src/p1/ConfirmationPage.js
- frontend/src/utils/queriesAndMutations.js
re #521 
add a `source` field to the data. value set to `p1` on submission for prototype 1.
> add source label to data

- platform/base/cybercrime-api-deployment.yaml
- platform/base/cybercrime-frontend-deployment.yaml
- platform/base/kustomization.yaml
> Pull from gcr.io

- frontend/locale/en/messages.json
- frontend/locale/fr/messages.json
- frontend/src/Home.js
- frontend/src/RootLandingPage.js
- frontend/src/components/layout/index.js
links to the two prototypes, so the site doesn't look broken.
> Root landing page

- README.md
Add instructions/command to run the front-end in dev mode.
> Update README.md with front-end instructions

- baseline/public/CAFCFRS/assets/translations/locale-en.json
- baseline/public/CAFCFRS/index.html
- baseline/public/index.html
This commit removes the word CAFC from our clone to minimize confusion.
> Remove obvious CAFC references

- frontend/locale/fr/messages.json
Adding text back in to replace 2222
> P1 glitch -- French line disappeared

- api/schema.graphql
- api/src/GraphqlTypes.js
- frontend/src/p2/ImpactStatementPage.js
- frontend/src/utils/queriesAndMutations.js
- fix GraphQL type name mismatch
To test, locally run `make dev`. Go through P2 frontend and the data will be inserted into arango.
> Fix up P2 frontend -> api

- frontend/src/p2/ConfirmationPage.js
- frontend/src/p2/ContactInfoPage.js
- frontend/src/p2/ImpactStatementPage.js
- frontend/src/p2/ScammerDetailsPage.js
- frontend/src/p2/TimeFramePage.js
- frontend/src/p2/WhatHappenedPage.js
- frontend/src/p2/forms/ContactInfoForm.js
- frontend/src/p2/forms/TimeFrameInfoForm.js
> Progressbar

- frontend/src/p2/forms/ContactInfoForm.js
- frontend/src/p2/forms/TimeFrameInfoForm.js
add all the " cancel" buttons at the button of pages link to p2  landing page
> all the " cancel" button link to p2  landing page

- frontend/locale/en/messages.json
- frontend/locale/fr/messages.json
- frontend/src/components/backbutton/index.js
- frontend/src/p2/ConfirmationPage.js
- frontend/src/p2/ContactInfoPage.js
- frontend/src/p2/ImpactStatementPage.js
- frontend/src/p2/ScammerDetailsPage.js
- frontend/src/p2/TimeFramePage.js
- frontend/src/p2/WhatHappenedPage.js
add "back" button under progress bar links to previous page
> Backbutton

- baseline/randomizeString.js
- baseline/server.js
> Anonymize baseline form data.

- baseline/package.json
`npm run dbg` just like our other services.
> Add a debug script to the baseline app.

- frontend/src/p1/forms/ScamInfoForm.js
- frontend/src/p2/ConfirmationPage.js
save date date on confirmation page for p1. allow to delete current date and keep date blank.
Fixes Issue #654
> Savedateconfirmationpage

- frontend/src/p2/ConfirmationSummary.js
> Translate impact types

- frontend/src/p2/ConfirmationPage.js
change "p1" to "p2" for prototype 2 source
> Fix source of prototype 2 data

- baseline/server.js
> Remove console.log statement

- frontend/src/p1/ConfirmationPage.js
> translate checkbox and radio button values on confirmation page

- baseline/public/CAFCFRS/assets/js/google-analytics.js
This commit adds a dirty hack to ensure we are capturing Angular's calls to
pushstate with Google Analytics.
> Monkey patch the history object, and profit!

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/TextInput/__tests__/TextInput.test.js
- frontend/src/components/TextInput/index.js
I'll be using this in a followup PR.
> Add TextInput component

- api/schema.graphql
- api/src/schema.js
- frontend/src/p1/ConfirmationPage.js
- frontend/src/p1/LandingPage.js
- frontend/src/utils/queriesAndMutations.js
resolves #714 
to verify, run via `make dev` and navigate to 
http://localhost:3000/p1?surveyID=surv11&ResponseID=resp1
> save surveyinfo in p1

- api/index.js
- api/package-lock.json
- api/package.json
This library logs to stackdriver, which is already happening when this is run
on GKE.
> Remove logger

- frontend/src/p1/LandingPage.js
- frontend/src/p1/forms/ScamInfoForm.js
- frontend/src/p2/LandingPage.js
- frontend/src/p2/forms/ImpactStatementInfoForm.js
- frontend/src/p2/forms/ScammerDetailsForm.js
- frontend/src/p2/forms/TimeFrameInfoForm.js
- frontend/src/p2/forms/WhatHappenedForm.js
- frontend/src/utils/queriesAndMutations.js
resolves #712 and #672 
remove datepicker from p2, replace with a single text box.
> Scrap date picker in P2

- frontend/src/p2/forms/ContactInfoForm.js
- frontend/src/theme/index.js
This commit makes this change for p2.
> Use input of type text instead of text areas

- frontend/src/components/TextInput/index.js
- frontend/src/components/input/index.js
- frontend/src/p1/forms/ContactInfoForm.js
- frontend/src/p1/forms/MoneyLostForm.js
- frontend/src/p1/forms/SuspectInfoForm.js
- frontend/src/theme/index.js
> Replace text areas with inputs of type text

- frontend/src/p1/forms/ScamInfoForm.js
- frontend/src/p2/forms/TimeFrameInfoForm.js
rather than textareas
https://rac-prototype-pr-728.herokuapp.com/p1/scaminfo
https://rac-prototype-pr-728.herokuapp.com/p2/timeframe
> use TextInputs for date inputs

- platform/base/cybercrime-api-ingress.yaml
- platform/base/cybercrime-frontend-ingress.yaml
We'll revert this after the testing.
> Remove frame-deny header to facilitate testing.

- frontend/src/client.js
- frontend/src/server.js
fixes bug where if you reload the confirmation page the submit button doesn't work.
> add surveyInfo defaults

- baseline/package-lock.json
- baseline/package.json
- baseline/server.js
> Rework baseline app to handle multiple users

- frontend/utils/mungeData.js
To process survey results and get some wordcount stats.
```
Usage:
node utils/mungeData.js data.json
or
node utils/mungeData.js data.json stats
```
> add munging utility

- api/Dockerfile
- frontend/Dockerfile
upgrading the version of alpine that is being used in our dockerfiles due to a severe known vulnerability.
See:   [https://app.snyk.io/share/3d46eb46-1739-4957-a590-34bc12044d75]
> upgrade alpine in dockerfiles

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
add application insight for MpSCNc3Rg project in Azure.add instrument key in App.js. not sure if it work in Azure, need merge to master first, then see if it works.
> add application insight for MpSCNc3Rg project.add instrument key in

- api/Dockerfile
- frontend/Dockerfile
> Dockerfile upgrade

- frontend/src/p1/LandingPage.js
- platform/overlays/aks/kustomization.yaml
more explicit kustomization for aks
> Aks pull test

- platform/overlays/aks/kustomization.yaml
"latest" is now 2.0 and our config is for 1.7.
> Add version to traefik

- frontend/src/RootLandingPage.js
- frontend/src/p1/forms/ScamInfoForm.js
- frontend/src/p2/forms/ImpactStatementInfoForm.js
- frontend/src/p2/forms/ScammerDetailsForm.js
- frontend/src/p2/forms/TimeFrameInfoForm.js
- frontend/src/p2/forms/WhatHappenedForm.js
- frontend/src/theme/index.js
> Fix a11y issues

- frontend/src/components/buttons-container/index.js
- frontend/src/p2/LandingPage.js
> Fix link button

- .gitignore
- platform/overlays/eks-no-tls/arango-claim.yaml
- platform/overlays/eks-no-tls/azure-storageclass.yaml
- platform/overlays/eks-no-tls/cybercrime-api-ingress.yaml
- platform/overlays/eks-no-tls/cybercrime-frontend-ingress.yaml
- platform/overlays/eks-no-tls/eks-default-storageclass.yaml
- platform/overlays/eks-no-tls/kustomization.yaml
- platform/overlays/eks-no-tls/traefik-ingress-controller-deployment.yaml
- platform/overlays/eks-no-tls/traefik-ingress-controller-service.yaml
This allows us to bring up the service on Amazon's EKS service.
> Add eks config

- frontend/package-lock.json
- frontend/package.json
we haven't used it in an alpha or so.
> remove recharts dependancy

- api/package-lock.json
> Fix api vulnerability

- frontend/src/components/topbanner/index.js
resolves #812 
add a link from the branding to RCMP's page.
> add link to RCMP to RCMP branding

- .github/workflows/test_f2.yml
- f2/src/__tests__/ConfirmationSummary.test.js
- f2/src/__tests__/ContactInfoPage.test.js
- f2/src/__tests__/ImpactStatementPage.test.js
- f2/src/__tests__/LandingPage.test.js
- f2/src/__tests__/ScammerDetailsPage.test.js
- f2/src/__tests__/TimeFramePage.test.js
- f2/src/__tests__/WhatHappenedPage.test.js
- f2/src/components/backbutton/_tests_/backbutton.test.js
- f2/src/components/buttons-container/_tests_/buttons-container.test.js
- f2/src/components/phase-banner/__tests__/PhaseBanner.test.js
- f2/src/components/stepper/_tests_/Stepper.test.js
- f2/src/components/topbanner/__tests__/TopBanner.test.js
- f2/src/components/warning-banner/__tests__/WarningBanner.test.js
- f2/src/forms/__tests__/ContactInfoForm.test.js
- f2/src/forms/__tests__/ImpactStatementInfoForm.test.js
- f2/src/forms/__tests__/ScammerDetailsForm.test.js
- f2/src/forms/__tests__/TimeFrameInfoForm.test.js
- f2/src/forms/__tests__/WhatHappenedForm.test.js
~~not sure how it was passing in the branch without a `lingui compile` but here we are.~~
Ah, I changed lingui to `minimal` style in master, which was causing the action to fail. OK, this should things...
> compile lingui before testing app

- app.json
change buildpack used for review apps since f2 uses create-react-app.
> use create-react-app buildpack for review apps

- frontend/package-lock.json
had some vulnerabilities creeping in
> frontend npm audit fix

- f2/utils/azurescript
…add Running this script will automatically create an azure container registry, Azure Cosmos DB account, the app service plan and the app service in the RCMP Azure. All the resource lie in "RCMPCDSCybercrimeRG" resource group.
> Azurescript for Cosmos DB account and app service plan

- f2/src/App.js
- f2/src/components/footer/index.js
> stick footer to bottom of window and make it smaller

- f2/src/ConfirmationPage.js
- f2/src/ContactInfoPage.js
- f2/src/ImpactStatementPage.js
- f2/src/ScammerDetailsPage.js
- f2/src/TimeFramePage.js
- f2/src/WhatHappenedPage.js
fix the accessibility issue"1 of 6 is not labelled as a header, blind participants don't know how many steps are next"
> fix the accessibility issue for stepper for all pages

- f2/azure-pipelines.yaml
new azure pipeline to reflect tech stack changes
> updated pipeline

- f2/src/LandingPage.js
> test pipeline

- f2/src/LandingPage.js
Reverts cds-snc/report-a-cybercrime#997
Changed my mind!
> Revert "test pipeline"

- f2/azure-pipelines.yaml
As discussed, added some comments to pipeline yaml
> Added comments to pipeline yaml

- f2/Dockerfile
Ran docker build & docker run on local machine and clicked through application. Doesn't seem to break anything?
> Upgrade nodejs version in Dockerfile

- f2/utils/checkTranslations.js
move checktransTranslation.js from src/utils  to utils folder
> move checktransTranslation.js from src/utils  to utils folder

- f2/utils/azurescript
> Removing admin access to acr

- f2/src/Home.js
- f2/src/LocationPage.js
- f2/src/forms/LocationInfoForm.js
- f2/src/locales/en.json
- f2/src/locales/fr.json
> Location page

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/new-feature.md
- .github/ISSUE_TEMPLATE/technical-debt.md
- .github/PULL_REQUEST_TEMPLATE.md
Some issue and PR templates to help us communicate and document our work. These will evolve as needed.
> add templates

- f2/src/BusinessPage.js
- f2/src/forms/BusinessInfoForm.js
use global state management in businessInfo form
Fixes #1048
> Please delete options that are not relevant.
> used new global state in businessInfo

- f2/src/App.js
- f2/src/components/footer/index.js
- f2/src/components/wordmark/__tests__/WordMark.test.js
- f2/src/components/wordmark/index.js
IE "flex" defaults are "1 1 0px". Compared to other browsers which is "1 0 auto"
Set the flex property on the main content to "1 0 auto"
> Fix main content flex

- f2/src/DevicesPage.js
- f2/src/forms/DevicesForm.js
change Devices page and form to use new global state 
Fixes #1049 
- [ x] Technical debt
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
--need create new unit test for the file, which is related to issue #1045
> use new global state in Devices page and form

- f2/src/__tests__/DevicesPage.test.js
- f2/src/forms/__tests__/DevicesForm.test.js
add unit test  for device page and device form
Fixes #1045 
- [Yes ] Technical debt
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] New and existing unit tests pass locally with my changes
> add unit test  for device page and device form

- f2/src/__tests__/BusinessPage.test.js
- f2/src/forms/__tests__/BusinessInfoForm.test.js
created unit test for business page and businessInfo form.
Fixes #1044
> Please delete options that are not relevant.
> add test for business page

- f2/src/ConfirmationSummary.js
- f2/src/locales/en.json
- f2/src/locales/fr.json
- f2/src/summary/ContactInfoSummary.js
- f2/src/summary/__test__/ContactInfoSummary.test.js
New summary block for Contact Details
Start at https://rac-prototype-pr-1100.herokuapp.com/confirmation
Then edit Contact Details at bottom
Fixes #1086 
French content
> Summary block for Contact Details

- .github/workflows/deploy_f2.yml
fix master maybe
none (hopefully!)
> change node version in deploy script

- f2/src/LandingPage.js
clear doneforms on landing page
Fixes #1067 
none
> clear doneForms on landingPage

- f2/src/forms/EvidenceInfoForm.js
Tweaks to the evidence upload page
Fixes #1122
I'm not sure what the status message does. I tested it with voice over on chrome with no success. Should test on safari
> evidence page ui fixes

- f2/src/components/FormHelperText/index.js
- f2/src/components/FormLabel/index.js
- f2/src/components/text-area/index.js
- f2/src/forms/WhatHappenedForm.js
Fixing some imports on the whatHappenedForm
Fixes #1010
> fixing imports on whatHappenedForm, max width on text area and labels

- f2/src/HowDidItStartPage.js
- f2/src/WhatWasAffected.js
Fix two broken back links.
Fixes #1107
none
> fix 2 back links

- f2/src/components/warning-banner/index.js
>This is a temporary workable solution until I refactor the component 
Fixes # (issue)
> Please delete options that are not relevant.
- [] New feature
- [Yes] Bug fix
- [Yes ] My code follows the style guidelines of this project
- [Yes ] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
> Will need to follow up with @amazingphilippe  the refactor work if needed.
> Add Trans to our warning banner - a working solution until refactor this component

- f2/src/summary/HowDidItStartSummary.js
add a space on confirmation page start block
> added a space in start summary

- f2/src/PrivacyConsentPage.js
Replaced privacy page Lead with P
Fixes #1141
> removed lead from privacy page

- app.json
- f2/src/LandingPage.js
Heroku's new Review Apps needs some configuration changes on our end. Review apps won't work until this PR merges 😞 
none - I've already done the required Heroku reconfiguration. That's what broke stuff in the first place! 😛
> Config requirements for new Heroku review apps

- f2/azure-pipelines.yaml
I have added some comments
Fixes # (issue) No Issue for this
> Comments added to pipeline

- f2/utils/azurescript
Added the commands to create the AV scanner to the environment build script.
Fixes # N/A
Actually testing this entire script by rebuilding the environment from scratch.
> Adding Virus Scanner to Environment build script

- f2/src/__tests__/FeedbackPage.test.js
Added test for FeedbackPage.
Fixes #1196
None
> Added test for FeedbackPage.

- utils/azurescript
Added azure script to create content moderator
> Please delete options that are not relevant.
N/A
> Added content moderator creation script

- f2/Dockerfile
Fix a newly discovered vulnerability in Node.
changes the version of Node used in the app from 12.14 to 12.15.
> upgrade node

- utils/azurescript.sh
Fixes https://trello.com/c/plg9f3WY
I am adding the creation of a VNET and SUBNETs for me to eventually associate to the Azure resources.
I have tested these commands individually and they work!
> Add VNET and SUBNETS

- f2/src/ThankYouPage.js
- f2/src/locales/en.json
- f2/src/locales/fr.json
Fixes #1413 
fix the link to the feedback page on the thankyou page
> make link work

- f2/src/locales/fr.json
Something got pasted in the wrong spot
> Typo in banner in FR

- f2/src/forms/HowDidItStartForm.js
- f2/src/locales/en.json
- f2/src/locales/fr.json
A few strings got deleted somehow
There was supposed to be a test to catch this - must go back and look at that test that isn't working.
> restore missing lingui strings

- utils/azurescript.sh
Changes to the Azure CLI to rename resources and tag them.
> Resource tagging

- f2/src/forms/HowDidItStartForm.js
Fixes #1313
Clears conditional fields on "How did it start" page if the checkbox is cleared and the form is submitted.
> clear condition fields appropriately

- f2/src/forms/MidFeedbackForm.js
Fixes #1469 
Fixes #1520
Close the mid feedback form after submission and display the "thank you" message
> close MidFeedbackForm

- utils/azurescript.sh
> Changing names back

- f2/azure-pipelines.yaml
I haven't tested it - We'll have to deploy and hold our butts.
> Update Build Arg Variable

- f2/azure-pipelines.yaml
Revert pipeline back to three pipelines now that shadow / meta config has been updated.
> Revert pipeline back

- f2/src/utils/encryptedEmail.js
- f2/src/utils/formatAnalystEmail.js
Fixes #1577 
If clam detects a virus, don't email to the analysts and log that it happened.
> Dont email viruses

- f2/src/forms/EvidenceInfoForm.js
- f2/src/locales/en.json
- f2/src/locales/fr.json
- f2/src/utils/encryptedEmail.js
- f2/src/utils/formatAnalystEmail.js
```
git clone git@github.com:cds-snc/report-a-cybercrime.git
cd report-a-cybercrime
git pull
git checkout release-rcmp-prod
git pull
git checkout -b update-prod-from-master
git merge -Xtheirs origin/master
git push
git push --set-upstream origin update-prod-from-master
git diff master update-prod-from-master
git status
git add .
git commit --amend --no-verify
git push -f
```
> Update prod from master

- f2/src/components/header/presets.js
Fixes #1310 
Increased a bit the line height on h1 preset
> increased line height on h1 preset

- f2/src/PrivacyStatementPage.js
Fixes #1394 
fixed up the privacy page a little bit
> fixed spacing issues on long privacypage

- f2/src/forms/MidFeedbackForm.js
- f2/src/forms/__tests__/MidFeedbackForm.test.js
Fixes #1594 
Added page pathname to identify where the feedback is coming from
> added location to identify which page the feedback came from

- f2/src/utils/encryptedEmail.js
Add a warning to the emails if file has been flagged.
```
NCFRS - ref NCFRS-23452352 WARNING: Adult Attachment
```
> Flag cm in subject

- .github/ISSUE_TEMPLATE/new-feature.md
- .github/ISSUE_TEMPLATE/suggestion.md
- .github/PULL_REQUEST_TEMPLATE.md
Add a "Suggestion" template to make it easier to just suggest changes that are unrelated to planned new features, bugs, or tech dept.
> add new issue template

- f2/src/PrivacyStatementPage.js
- f2/src/locales/en.json
- f2/src/locales/fr.json
Necessary to ensure compliance with the _Directive on Privacy Practices_ s.6.2.9. Put it under a new heading on Keith E's recommendation (he happened to be at my desk).
n/a
n/a (as far as I know)
> Update privacy statement to mention RCMP Act

- f2/src/ThankYouPage.js
Fixes #1609 
> open new tabs for links under thank you page where you can find help
> no
> no
> new page should be opened

- f2/src/locales/en.json
Adding one word to the information page:
How **did** they ask for or obtained information?
> Minor copy change (typo)

- f2/server.js
Add some extra console.logs to try to figure out what's pinging our app. Does the first 20 requests then stops printing out.
revert this PR when not needed anymore
> temporarily enable request debugging

- f2/package-lock.json
- f2/package.json
- f2/server.js
Fixes #1323 
> We should probably use Helmet to set our HTTP headers to recommended values. 
> yes, Helmet
> no
> Use Helmet

- f2/src/forms/ContactInfoForm.js
- f2/src/locales/en.json
- f2/src/locales/fr.json
Fixes #1230 
> If the input is empty, it is considered optional, therefore a value of empty validates
If the input is not empty, it should validate against a predefined pattern. address@email.domain or 613 123-4567
> final-form
>
> Validation for contact details

- f2/src/forms/LocationInfoForm.js
Fixes #1714 
> Validation for postal code using final-form.
> no
> validation for location page

- f2/src/utils/formatAnalystEmail.js
Fixes #1720 
Improve "They asked for" and "I lost" lines in analyst email:
> tweak email

- f2/src/__stories__/Forms.stories.mdx
- f2/src/components/DescriptionListItem/DescriptionListItem.stories.mdx
- f2/src/components/button/Button.stories.js
Added documentation for DescriptionListItem
Also fixed a bug in the button documentation, following changes in the form validation inner workings.
> Sb descriptionlist

- f2/src/LandingPage.js
- f2/src/PrivacyConsentPage.js
- f2/src/PrivacyStatementPage.js
- f2/src/TermsAndConditions.js
Fixes #1694 
Update NC3 / GNC3 links
> fix nc3 links

- f2/src/forms/ContactInfoForm.js
- f2/src/forms/__tests__/ContactInfoForm.test.js
Fixes #1752 and a little bit of #1758 
Tweak the phone number validation as in
https://www.w3resource.com/javascript/form/phone-no-validation.php
Also added a test for the validation
> tweak phone number validation and add tests

- f2/src/ThankYouPage.js
Fixes #1021 
Added the required GTM tag identifiers for reporting verification status located /thanYouPage
- Added a tag identifier for a successful report status
- Added a tag identifier for report failure message status
- Added screen readers feedback when a report error status occurs
- Added screen readers feedback when a successful report status occurs
- Added visual clues for the generated error 
Visual clue > not sure of the color selection @amazingphilippe 
> Give details
I will need to add a separate doc on GTM implementation requirement
- [YES ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or …
> [Need for launch]Added the required GTM tag identifiers

- f2/azure-pipelines.yaml
Adding GTM to the build pipeline.  Added to app service previously.
> adding gtm tag to build pipeline

- f2/azure-pipelines.yaml
Hotfix for the gtm tags to the pipeline
> adding gtm hotfix

- f2/src/components/phase-banner/index.js
> phase banner tag more obvious

- f2/src/utils/checkIfAvailable.js
- f2/src/utils/saveRecord.js
Fixes #1821
> when the day rolls over, we are not resetting the number of submissions nor letting CAFC redirect to us
> no
> no
> number of submissions and availability not rolling over with new day

- f2/src/locales/en.json
- f2/src/locales/fr.json
Untranslated strings have made their way into master. This fixes it.
> fixing translations

- f2/src/utils/formatAnalystEmail.js
Fixes #1844
> The following information is displayed twice in the analyst email
Report Version
When did it start
> no
> no
> Duplicate information is displayed in the analyst email

- f2/server.js
- f2/src/i18n.config.js
Fixes #1830
We were looking for the wrong url when deciding whether to serve the French or English page
> recognize French url

- f2/src/ConfirmationPage.js
- f2/src/FinalFeedbackPage.js
- f2/src/ThankYouPage.js
- f2/src/components/EditButton/__tests__/EditButton.test.js
- f2/src/components/EditButton/index.js
- f2/src/forms/ConfirmationForm.js
- f2/src/forms/defaultValues.js
- f2/src/utils/state.js
apply submission fix #1863 to the current staging branch
> Move submitted and reportId out of formData (#1863)

- .github/workflows/deploy_storybook.yml
CI deploy of storybook is failing 😞 
To test this I changed the name of the required branch to this branch. Then the deploy will run when new commits come into this branch, as you can see from the tests run on all but the last commit (where I changed the required branch back to master)
> Fix storybook CI deploy

- f2/src/Home.js
Fixes #1957(issue)
redirect user to privacy consent page instead of report flow if user cancel report in anonymous page
> Give details
> redirect user to privacy consent page if user cancel report in anonymous page

- f2/src/utils/state.js
Update the hard coded version number in staging
> Updated the hard coded version for June-4 release (#1991)

- f2/src/utils/state.js
* Updated the hard coded version for June-4 release
* Removing the dev notation
Co-authored-by: khalid <khalo>
Fixes #(issue)
> Give details
> Removing the dev App version notation (#1996)

- f2/.env.example
- f2/server.js
- f2/src/utils/encryptedEmail.js
- f2/src/utils/formatAnalystEmail.js
- f2/src/utils/saveBlob.js
Pushing e-mail fix to staging so it can be included in 1.4 build.
> Encrypted E-mail and attachments redesign (#1975)

- .github/PULL_REQUEST_TEMPLATE.md
I didn't know if I should commit to master or if the .github was ignored from the build, either way, I made a PR for it.
> Add reminder for env vars

- utils/azurescript.sh
This is a backfill of recently added Environment variables to the script which builds the Environment.  I have ran the updated commands individually against staging environment so they have worked as written.
> Updating Environment Variables

- f2/CHANGELOG.md
> Update changelog for 1.4

- f2/server.js
> Remove CSP for now until tested more

- f2/src/utils/selfHarmWordsScan.js
Fixes #1976 
Use regex to find exact matches for key words.
N/A
N/A
> Keyword fine tuning

- f2/Dockerfile
Fixes #2010(issue)
Upgrade Dockerfile node from 12.15 to 12.18
> upgrade Dockerfile node from 12.15 to 12.18

- f2/src/App.js
Fixes #2059(issue)
we change to open a new browser after click " Return to the previous version."
> open a new brower after  clicking the link

- f2/src/utils/selfHarmWordsScan.js
Fixes #2063 
PR #2041 adds a stemmer to identify root words. This update will use the English or French stemmer depending on language of submission. 
N/A
N/A
> Attach stemmer based on language

- f2/src/utils/state.js
Fixes #2056(issue)
change version from 1.4.0 to 1.5.0 
> change version to 1.5.0

- f2/src/utils/state.js
Cherry picked Diane's PR #2057 for staging.
> change version to 1.5.0 (#2057)

- f2/src/utils/state.js
Updating ver # for release 1.6
> Update version # for release 1.6

- f2/src/utils/scanFiles.js
Cherry picking PR #2087 
How I cherry-picked:
```
git checkout release-rcmp-staging
git pull
git checkout -b cherry-pick-2087
git cherry-pick 9ee776f9ac438ceb2638b3e568ae15c1c6b85692
git push
```
> No more offensive image (#2087)

- f2/CHANGELOG.md
Update changelog with changes from 1.5 and 1.6
> Changelog1.6

- f2/src/utils/state.js
> CHange version to 1.7

- f2/src/utils/scanFiles.js
> quick linting fix

- f2/src/components/formik/alert/index.js
- f2/src/forms/AnonymousInfoForm.js
- f2/src/theme/style.css
Fixes #2139 
Refactored form to use new Bootstrap components and Formik.
N/A
N/A
> Refactor Anonymous Info form

- f2/cypress/integration/generate_full_anony_report_en/generate_full_anony_report_en.js
- f2/cypress/integration/generate_full_anony_report_fr/generate_full_anony_report_fr.js
- f2/cypress/integration/generate_full_report_en/generate_full_report_en.js
- f2/cypress/integration/generate_full_report_fr/generate_full_report_fr.js
- f2/cypress/integration/generate_fyi_report_en/generate_fyi_report_en.js
- f2/cypress/integration/generate_fyi_report_fr/generate_fyi_report_fr.js
Fixes #(issue)
update cypress script to accommodate new form Formik 
> Give details
> updte cypress script

- f2/cypress/integration/generate_full_report_en.feature
- f2/src/forms/WhenDidItHappenForm.js
This update fixes a Cypress testing error. The datePicker IDs are now consistent with the test case.
> Update when did it happen

- f2/package-lock.json
- f2/package.json
Fixes #2267
> found 10615 vulnerabilities (10587 low, 1 moderate, 27 high) in 3339 scanned packages
run npm audit fix to fix 10609 of them.
1 vulnerability requires semver-major dependency updates.
5 vulnerabilities require manual review. See the full report for details.
> Give details
> Upgrade our dependencies. 

- f2/src/locales/en.json
- f2/src/locales/fr.json
Fixes #2240
>Inform the user to include the date they were contacted in the FYI flow on the ''What happened ?''page.
> Give details
> Include date contacted in What happened form for FYI flow

- f2/server.js
Fixes #(issue)
> Fix XSS vulnerability. In feedback forms, if you put <script>alert("Hello");</script> or <bold>Hey</bold> in as user input, it should be rendered correctly in the e-mail.
> Give details
> Fix XSS vulnerability

- f2/src/utils/imageConversion.js
Fixes #2285 
> Remove confusing logs.
> Give details
> Remove confusing logs

- f2/src/utils/scanFiles.js
Hotfix by john to improve error logging around virus scanning, and make sure a file is still persisted if the virus scan fails to run. (Not if a positive signature is found though)
> error logging and save uploaded files

- f2/src/utils/scanFiles.js
Cherry-picks commit #d4f907b48a35c6e9dbc593b9987e7304b80c9633 into prod. 
(John's hotfix for virus scanning logging and file recovery)
> error logging and save uploaded files (#2321)

- f2/package-lock.json
- f2/src/forms/WhenDidItHappenFormSchema.js
- f2/src/forms/__tests__/WhenDidItHappenForm.test.js
Fixes #2253 
Allows user to continue without making a selection, also allows omitting dates. Dates are still validated.
N/A
N/A
> When did it happen validation

- f2/src/forms/PrivacyConsentInfoForm.js
- f2/src/locales/en.json
- f2/src/locales/fr.json
Fixes #2335 (issue)
This is to fix Consent title replaced with undefined in analyst report. 
After fix, Consent Title and Value are displayed correctly both in English and French
> Give details
> PR2335 Fix issue of Consent Replaced With Undefined

- f2/src/utils/state.js
Update the version # label in the page template.
> Update version # in template 1.7->1.8

- f2/src/forms/LocationInfoForm.js
Fixes #2334 
This is to fix spacing issue introduced in LocationForm.
Implement matching better spacing between row using new formik row
> Give details
- [X ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
> PR2334FixingLocationPageSPacing

- f2/azure-pipelines.yaml
Staging and Dev should use a different GTM ID.
> Change GTM ID for staging and dev

- f2/src/pdf/DescriptionItemView.js
Fixes #2405 
> Fix the problem that the data field is not aligned with title field in PDF report
> Fix Title data alignment in PDF report

- f2/src/utils/formatAnalystEmail.js
Fixes #2437 (issue)
This is to fix incorrect missing field warning in analyst report
> Give details
- [X ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)
> Solve wrong missing fields warning in analyst report
