frontend/.prettierrc

Setting the parser to babylon was useful many moons ago for something to do
with JSX.  This config was kept because there was never a reason to change it,
but it turns out that it doesn't parse json well which, mixed with husky
pre-commit hooks blocked me from commiting.  This fixes the issue by simply
removing the stated preference for babylon.

Remove parser specification

---

ingress/manifests/overlays/gke/traefik-ingress-controller-deployment.yaml
ingress/manifests/overlays/gke/traefik-ingress-service.yaml
ingress/manifests/overlays/minikube/kustomization.yaml
ingress/manifests/overlays/minikube/traefik-ingress-controller-deployment.yaml

This commit disables the traefik dashboard on GKE and enables it on Minikube
since it's useful for debugging.

Refine ingress config

---

api/README.md
api/manifests/base/arangodb-claim0-pvc.yaml
api/manifests/base/arangodb-deployment.yaml
api/manifests/base/arangodb-service.yaml
api/manifests/base/cybercrime-api-deployment.yaml
api/manifests/base/cybercrime-api-ingress.yaml
api/manifests/base/cybercrime-api-namespace.yaml
api/manifests/base/cybercrime-api-service.yaml
api/manifests/base/kustomization.yaml
api/manifests/overlays/gke/arango-claim.yaml
api/manifests/overlays/gke/cybercrime-api-service.yaml
api/manifests/overlays/gke/kustomization.yaml
api/manifests/overlays/gke/ssd-storageclass.yaml
api/manifests/overlays/minikube/arango-claim.yaml
api/manifests/overlays/minikube/cybercrime-api-service.yaml
api/manifests/overlays/minikube/kustomization.yaml

Moving the API and db into the cybercrime-api namespace, and fixing the storage so that Arango is using ssd. Updated the readme with relevant instructions.

Namespace api

---

api/package.json
api/setUpJest.js
api/src/Stats.js
api/src/__tests__/database.test.js
api/src/__tests__/schema.test.js
api/src/__tests__/server.test.js
api/src/dbinit.js
api/src/schema.js

This commit adds a stats field to the query schema allowing users to as for the
total number of reports with a query like this:
```graphql
{
stats {
reportCount
}
}
```

Add stats field to query schema

---

.editorconfig
Makefile
api/index.js
docker-compose.yml

This commit adds a docker-compose file to bring up a working development environment.
I've added a make file to simplify things a little further, which leaves us with two simple commands to get things going:
```sh
make setup
DB_USER=root DB_PASSWORD=test make dev
```
This will bring up the frontend listening on localhost:3000, the API, at
localhost:3000/graphql and ArangoDB, with it's admin interface on
localhost:8529.
The first time you run this you will need to log into arangodb and create a database (called cybercrime) and a collection (called reports).

Use docker-compose for local dev

---

frontend/package.json

This field was missing which caused the warning:
```sh
npm WARN report-a-cybercrime@0.0.1 No repository field.
```
This simply adds the missing field which resolves the problem.

Add repository field to package.json

---

frontend/src/LanguageSwitcher.js
frontend/src/__tests__/LanguageSwitcher.test.js

This commit changes the LanguageSwitcher component to output a button. The
previous "a" element had no href attribute (since it wasn't navigating
anywhere) and was therefore not included in the accessibility tree. Switching
to a button fixes this and closes #63

Change LanguageSwitcher to a button

---

ingress/manifests/traefik-ingress-controller-deployment.yaml

This commit sets the TLS minimum version to 1.2 and specifies the ciphers
available. The ciphers available are the ones defined in Go's tls library:
https://golang.org/src/crypto/tls/cipher_suites.go
The current configuration gets and A+ from SSLLabs.

Improve TLS settings

---

frontend/cloudbuild.yaml

This commit ensures that language file are created before tests are run by cloudbuild.

Fix frontend cloudbuild

---

frontend/src/App.js

Add in Google's Roboto font, as recommended by Sam.
Uggh, there's some ugly due to the font being injected global with SSR removed, I believe. This will be fixed down the line as we will be assigning the font on a per component basis.

Add in 🤖-o font

---

frontend/.linguirc
frontend/locale/en/messages.json
frontend/locale/fr/messages.json
frontend/package.json

Instead of the default records that look like
```
"Bank accounts": {
"translation": "Comptes bancaires",
"origin": [["src/Screen2.js", 122]]
},
"Describe what happened": {
"translation": "Décrivez ce qui s'est passé",
"origin": [["src/Screen1.js", 41]]
},
```
use the minimal style, which looks like
```
"Bank accounts": "Comptes bancaires",
"Describe what happened": "Décrivez ce qui s'est passé",
```
This will make PRs that change these files less annoying in that they will not have all the line # changes in them.
Also deleted the `.linguirc` file while I was at it, as lingui is being configured in `package.json`.

Use minimal style for lingui json files

---

frontend/src/LandingPage.js
frontend/src/__tests__/ListItem.test.js
frontend/src/__tests__/OrderedList.test.js
frontend/src/__tests__/UnorderedList.test.js
frontend/src/components/list-item/index.js
frontend/src/components/list-item/presets.js
frontend/src/components/ordered-list/index.js
frontend/src/components/ordered-list/presets.js
frontend/src/components/unordered-list/index.js
frontend/src/components/unordered-list/presets.js

This PR adds components for unordered lists, ordered lists & list items! As per the usual, added an example on the landing page but left everything else untouched.

Add unordered lists, ordered lists & list items

---

frontend/src/LandingPage.js
frontend/src/__tests__/OrderedList.test.js
frontend/src/__tests__/UnorderedList.test.js
frontend/src/components/ordered-list/presets.js
frontend/src/components/unordered-list/index.js
frontend/src/components/unordered-list/presets.js

@sastels made a really good point that being able to pass listStyleType as a prop would be much nicer syntax, so... here it is! Now both Ordered and Unordered lists will accept any legitimate list style type (https://www.w3schools.com/cssref/pr_list-style-type.asp) as a prop, but default to number and disc respectively (since these are by far the most used types. Passing in none results in a special list with no left padding. 
Also I tested ordered lists on the landing page and realized.... I really like it as an ordered list, since it's a step by step list! So I left it in :)

Refactor lists to accept listStyleType prop

---

frontend/src/LandingPage.js
frontend/src/__tests__/Link.test.js
frontend/src/components/link/index.js
frontend/src/utils/asAnchor.js

This PR adds: 
- asAnchor, an HoC that is used to return a styleable link component
- Link, a styleable Reach Router Link created using asAnchor
- A, a styleable anchor created using asAnchor

Add Link components & hoc

---

frontend/src/Screen1.js
frontend/src/__tests__/Text.test.js
frontend/src/components/text/index.js
frontend/src/components/text/presets.js

a styled div. Uses paragraph defaults, can also give it a `display` prop to override the default `block` styling (ie for inline text)
Example in breadcrumb text on first form ("Placeholder" and "for" are inline, "Breadcrumb" is default and bigger)

add styled Text component

---

frontend/src/components/container/__tests__/Container.test.js
frontend/src/components/container/index.js

This PR adds a general use styled div called Container, used to uh, contain... things. I've added the props necessary to handle my upcoming Top Header component, mostly flexbox and basic height/width things. We will likely need to add onto this in the future for more complex layouting, but this gives us a start. Also, check out them tests ;)

Add a Container component

---

frontend/src/server.js

Resolves #150 
Note that you might have to also manually unregister the old service worker for localhost from your browser. (that are lurking around from the last time you ran locally). They're a tough beast to get rid of.

disable service workers unless in production

---

frontend/.babelrc
frontend/package-lock.json
frontend/package.json

In this version Jest no longer auto injects regenerator-runtime so this commit
includes some babel config changes to ensure that async/awat still works in our
tests.
The full list of changes are described here:
https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly

Update to Jest 24.1.0

---

frontend/src/App.js
frontend/src/components/topbanner/__tests__/TopBanner.test.js
frontend/src/components/topbanner/index.js

_finally_
This PR adds a responsive Top Banner component using the Container, GoCSig & LanguageSwitcher components. Discussed the issues of aria-label/aria-describedby/alt text etc with @JuliannaR, there's some kind of issue there with the screen reader not picking up the SVG as an image, but that's something we an solve down the line when we swap out for the RCMP logo and potentially add a link back to the RCMP website, changing the behaviour.

Add Top Banner component

---

frontend/cloudbuild.yaml

jest breaking on CI. Downgraded node on testing to 11.10-alpine, as per
https://github.com/facebook/create-react-app/issues/6591

downgrade node version in cloudbuild tests to fix master

---

api/cloudbuild.yaml

jest breaking on CI. Downgraded node on testing to 11.10-alpine, as per
facebook/create-react-app#6591

roll back node version in api, new version breaks jest

---

frontend/.eslintrc.json

Import plugin rules were off by default, so while we had this plugin installed
it wasn't functioning. This commit adds the necessary options to our eslint
config.

Add config to enable import linting

---

frontend/package-lock.json
frontend/package.json

PR #185 started using the dev dependency `unfetch` in prod code. This PR moves `unfetch` to be a prod dependency.

Fix unfetch dependancy

---

frontend/public/service-worker.js

the graphql POSTs were causing the `service-worker` code to throw an error. In this PR we restrict the caching to GETs.

don't cache graphql calls in service-worker

---

frontend/.eslintrc.json
frontend/package.json
frontend/src/Screen2.js
frontend/src/components/input/__tests__/Input.test.js
frontend/src/components/text-area/__tests__/TextArea.test.js

This commit/linter is just for testing and exploration purposes to see what can work as a standard Accessibility linter tool.
Notes:
- It will be only tested with all A11y baked in rules within the linter for common aria* validations
- Any custom rules for styled components will be added later with more feedback from the team :)

Added jsx-a11y Linter 

---

frontend/package.json

In this PR I'm adding the Lingui compile step to the dev and test commands. This is to solve an issue where trying to run the app in dev or running certain tests will give weird errors if you forget to compile after cloning, or if another PR changes the messages and you don't compile locally. Compilation doesn't take all that long and solves flaky tests so, maybe worth it?

Add Lingui to dev & test command (maybe?)

---

frontend/src/App.js
frontend/src/Screen1.js
frontend/src/components/skip-link/__tests__/SkipLink.test.js
frontend/src/components/skip-link/index.js

resolves #142 
Basically a glorified `<A />`. Adds an `invisible` prop that will make the link invisible if not in focus.
CSS adapted from https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/mouse-and-keyboard-events/skip-to-main-content/
Example of usage is at the bottom of the first form of the discovery tool, `/old/form1`

Skip links

---

frontend/src/TrackPageViews.js

addresses #204 
for now, add the current GA id as the default. note that the GA id is not confidential (it's included in the bundle)

add current GA id as default

---

frontend/src/Page1.js
frontend/src/Page2.js
frontend/src/Summary.js
frontend/src/components/link/index.js
frontend/src/utils/asAnchor.js

This PR replaces the buttons with a button esque styled Reach Link component, to fix the language flow of the app. This PR is a "quick fix" for testing tomorrow, and would require some refactoring after (some props are showing up from styled-system that shouldn't, not using steve's component, etc)

Replace Buttons with styled Reach Links

---

api/package-lock.json
api/package.json
api/schema.graphql
api/src/Stats.js
api/src/__tests__/database.test.js
api/src/__tests__/schema.test.js
api/src/__tests__/utils.test.js
api/src/dbinit.js
api/src/utils.js

This commit adds a new function to the graphql api that returns proper data for
the summary graph. "Proper" in this case meaning that it the user supplies a
date range and the summary includes days with 0 reports within the range.
This addresses #255 and will be followed with a commit to get the frontend
using this new function.

Serve better summary data

---

frontend/src/client.js
frontend/src/server.js

The Apollo cache was being created with default values for the narrative
gathering tool. This commit removes those and defaults the cached value for
language to "fr" if it can find it in the navigator.languages array.

Clean up cache creation

---

frontend/src/Chart.js
frontend/src/Stats.js
frontend/src/Summary.js
frontend/src/__tests__/Stats.test.js
frontend/src/utils/queriesAndMutations.js

This commit modifies the frontend to make use of the new flaggingsWithin
function exposed by the api. This will address some of the shortcomings with
the data visualization (ie, not displaying days with 0 reports).
The values for the demo are still hardcoded (ie the phone number identifier),
but the refactoring here will allow us to remove them and get this working for
real easily. This will be the focus of a followup PR.

Use better summary data

---

frontend/.prettierignore

Schema.graphql is meant to give a nice clean view of schema changes, as it gets
regenerated on each commit. Unfortunately since prettier reformats it every
time it's regenerated it ends up as noise in a lot of commits. Adding it to a
.prettierignore file will stop this.

Don't prettify api/schema.graphql

---

api/cloudbuild.yaml

This commit reworks the cloudbuild file, moving test credentials and such into
variables and adding a few missing variables.
You may also note that we are now using kaniko for image building. This is a
new tools that lets you build containers without docker, and it should give a
bit of a speed boost as well as making our images reproducable (ie, two images
with the same content build at different times would have the same SHA).

Refactor cloudbuild file

---

.gitignore
Makefile
README.md
api/src/__tests__/database.test.js
api/src/__tests__/mutations.test.js
api/src/__tests__/schema.test.js
api/src/__tests__/server.test.js
api/src/__tests__/utils.test.js
docker-compose.yml

The idea here is to simplify project setup by consolidating all the various
variables into a single place; your environment. Previously, we had been using
.env files, but these became awkward given shared variables, and the fact that
using them meant filling in variables in multiple places.
This commit basically drops these .env files for a single set of variables in
your `~/.bashrc` or `~/.bash_profile`. A minimal example of the new set of
variables would be:
```sh
export API_PORT=3002
export DB_NAME=cybercrime
export DB_PASSWORD=yourpassword
export DB_USER=root
export DB_URL=http://arangodb:8529
export TEST_DB_URL=http://localhost:8529
export RAZZLE_PORT=3000
export RAZZLE_GOOGLE_ANALYTICS_ID="UA-XXXXXXXXX-1"
export RAZZLE_SERVER_SIDE_API_URI=http://api:3002/graphql
export …
```

Refactor env var handling

---

api/cloudbuild.yaml

This commit adds an important variable to the cloudbuild config that allows the
test step to communicate with the arangodb test database started in the first
step.
A value for the $_TEST_DB_URL variable has already been defined in the API trigger on Cloudbuild.

Add TEST_DB_URL to cloudbuild

---

platform/.flux.yaml

This commit adds a config file for Flux to allow [manifest
generation](https://github.com/weaveworks/flux/blob/master/site/fluxyaml-config-files.md).
The idea here is that Flux runs within the cluster and generate config using
custom commands (kustomize!). This file controls the specifics of how that
works.

Add .flux file to control manifest generation

---

api/cloudbuild.yaml
frontend/cloudbuild.yaml

This commit adds an environmental variable to the cloudbuild config files that prevents [Husky](https://github.com/typicode/husky/blob/master/DOCS.md#disable-auto-install) from installing itself during the build process.

Disable husky githook install in CI

---

api/cloudbuild.yaml

Kaniko builds a bit faster and simplifies cloudbuild config a little by
automatically pushing images. Unfortunately it seems to build images that have
missing files, which then causes breakage downstream.
As an example:
https://github.com/GoogleContainerTools/kaniko/issues/362

Replace kaniko with docker build

---

frontend/package-lock.json
frontend/package.json
frontend/razzle.config.js

Removing because the bundle size plugin frequently fails and blocks our builds.
Integration has been removed in Github as well.

Remove size plugin

---

frontend/src/index.js

The compliance API is not currently running in the cluster so calling out to it
is useless.

Remove compliance api trigger

---

frontend/package-lock.json
frontend/package.json
frontend/razzle.config.js

This commit adds webpack-bundle-analyzer in dev mode so that we have some
better visibility into the contents of our bundles.
After running `npm run dev` you can find the output in
`build/bundle-analysis.html`.

Add webpack-bundle-analyzer

---

frontend/src/components/container/index.js

fixes #509 
maxwidth working again
No idea why it ever worked? Container didn't have a `maxWidth` prop (unless it being included automagically by something in styled-system that changed). Odd.

Fix pages' maxWidth

---

.github/main.workflow

This was something that the platform team made, but it often crashes master for no reason. We can always add it back if it is fixed.

stop linting dockerfiles

---

frontend/src/p2/TimeFramePage.js

This fixes the destination of the continue button to the WhatHappened page.
To test:
1. Go to P2
2. Go to timeframe page
3. Click Next -> should go to Whats Happened page.
Fix for #612

Fix next step for Timeframe

---

frontend/src/p1/forms/ScamInfoForm.js
frontend/src/p2/forms/TimeFrameInfoForm.js

This is a fix for allowing blank dates (Issue #598) in the Timeframe page (P2) and the Narrative Page (P1).
Fixed this by adding a check for null and length before parsing the string into a date.
You can test this by running the deployment, removing/erase/clear the date and then clicking continue.

Allow blank dates (Fix for Issue #598)

---

frontend/src/TrackPageViews.js

fixes #677 
This seems to be the way to tell GA about pageviews (see https://github.com/react-ga/react-ga#reactgapageviewpath). running locally with the GA id, the realtime data was registering the pageviews as pageviews.

register pageview using GA pageview method

---

frontend/src/p2/ConfirmationPage.js
frontend/src/p2/forms/ConfirmationForm.js
frontend/src/utils/queriesAndMutations.js

resolves #650 
remove "Tell Us More" box from confirmation page of prototype 2.
Currently it's just hacked out. If we really don't want any new inputs on the confirmation page, we can simplify the code by eliminating the `ConfirmationForm.js` file, moving the buttons from it to `ConfirmationPage.js`.

remove tell us more box

---

frontend/src/p1/forms/__tests__/ContactInfoForm.test.js
frontend/src/p1/forms/__tests__/MoneyLostForm.test.js
frontend/src/p1/forms/__tests__/ScamInfoForm.test.js
frontend/src/p1/forms/__tests__/SuspectInfoForm.test.js
frontend/src/p2/forms/__tests__/ContactInfoForm.test.js
frontend/src/p2/forms/__tests__/ImpactStatementInfoForm.test.js
frontend/src/p2/forms/__tests__/ScammerDetailsForm.test.js
frontend/src/p2/forms/__tests__/TimeFrameInfoForm.test.js
frontend/src/p2/forms/__tests__/WhatHappenedForm.test.js

These functions made it difficult to evolve the content without test breakage.
This commit removes almost all usage of these functions. The remaining cases
are either in p1 (soon to be deleted), the components folder (not effected by
content changes), or are cases where the text being searched for is supplied in
the actual test.

Replace getByText and getByLabelText

---

frontend/src/components/backbutton/index.js

fixed #813 
stop screen readers from pronouncing "black triangle" in the back links.
Note that I had to set the `aria-label` to a space, setting it to an empty string caused voiceover to again say "black triangle"

don't say black triangle in link

---

frontend/src/theme/index.js

fixes #814 
Darken up the blue we use a bit so links meet WCAG AAA.
old:
new:

use a darker blue

---

api/src/__tests__/server.test.js
api/src/server.js
platform/base/cybercrime-api-deployment.yaml

These checks allow Kubernetes to confim that the service is alive and ready to
handle traffic. Together with the values in `.spec.strategy.rollingUpdate` these
checks allow Kubernetes to replace existing pods only when new versions are
running and functional.

Add liveness/readiness checks to cybercrime-api

---

f2/src/App.js

resolves #922
We had two `<main>` blocks in `f2` (one inside the other). Removing the outer one fixed this, and is more semantically correct.

Stick footer to bottom of screen in f2

---

platform/azurescript.sh

create Azure script to spin up an environment for testing. The Azure script  allow us to create an Azure resource group,  AKS cluster, container registry, build an image in locally and in Azure,  push the image to ACR and pull the image from ACR to AKS cluster, create an Azure storage account and  Azure storage container.  Those multiple-task can be done at one time by just running the Azure script.

create Azure script to spin up an environment for testing

---

f2/src/forms/WhatHappenedForm.js

removed superfluous text from what happened form

---

f2/src/ConfirmationPage.js
f2/src/ConfirmationSummary.js

stop clearing the data on the thankyou page, This means in testing we can go back to the confirmation page and discuss the answers with the user.
might have to restore it later

dont clear data on thankyou page

---

f2/src/forms/HowDidItStartForm.js

Adds a little spacing between questions on `howdiditstart`
figure out why the spacing seemed too tight only on this page. Set a standard across the app. Set a global spacing variable for formControls

more spacing on how did it start page

---

f2/src/locales/en.json
f2/src/summary/BusinessInfoSummary.js
f2/src/summary/ContactInfoSummary.js
f2/src/summary/DevicesSummary.js
f2/src/summary/EvidenceInfoSummary.js
f2/src/summary/HowDidItStartSummary.js
f2/src/summary/InformationSummary.js
f2/src/summary/LocationInfoSummary.js
f2/src/summary/MoneyLostInfoSummary.js
f2/src/summary/SuspectCluesSummary.js
f2/src/summary/WhatHappenedSummary.js
f2/src/summary/WhatWasAffectedSummary.js
f2/src/summary/__tests__/MoneyLostSummary.test.js
f2/src/summary/__tests__/WhatWasAffectedSummary.test.js

As referenced in #1198 the text for the aria-labels wasn't marked for `npm run extract` to pick up. This fixes that.
Also adds 2 missing tests.
none, other than making sure in-flight PRs don't incorrectly delete these lines.

Mark edit button text

---

f2/server.js

change the server to add a route to tell CAFC if we're accepting reports or not. Currently just a prototype that alternates between accepting, not accepting, and 404. This is to allow CAFC to test the code they're building.
To test: locally run `node server.js` (instead of `npm run dev`) and go to `localhost:3000/available` 
Fixes #1201 
Still need to figure out and write the real logic for determining if we want another report.

rough in CAFC readiness code

---

utils/azurescript

Adding the commands to restrict access to the App Service exclusively from the Application Gateway
> Adding the commands to restrict access to the App Service exclusively from the Application Gateway.  Note, I took out the leading whitespaces in the script and so far github thinks those are all changes.  The real changes are the new variables at the top and the new commands at the bottom.
Fixes # (N/A)
> Test this entire script, not just the unit tests of individual command sections

Network Restrictions

---

f2/src/App.js

Fixes #1254 
Fixes an a11y issue where we had no main landmark region
There are still the app version number that needs to be between the footer and the main. Maybe consider choosing one of the two regions or making up a custom region

added as prop to main container

---

f2/server.js

Allow cross-origin requests if origin is antifraudcentre site
Nope
- [] I have added and needed tests for my changes (in particular for new screens)
Need to test it with CAFC.

Allow cross-origin requests from antifraudcentre

---

f2/src/forms/WhatWasAffectedForm.js
f2/src/locales/en.json
f2/src/locales/fr.json

Removing conditional 'Other' input field on 'What could be affected' page

Remove conditional 'Other' input field on what could be affected page

---

f2/src/summary/HowDidItStartSummary.js
f2/src/summary/MoneyLostInfoSummary.js
f2/src/utils/__tests__/formatDate.test.js
f2/src/utils/formatAnalystEmail.js
f2/src/utils/formatDate.js

Fixes #1489 
Fixes #1486 
Write a `formatDate(day, month, year)` function and use in the summary pages. Format empty inputs to an empty string, and omits leading slashes (ie if there's no day then just give month/year)

format date better

---

f2/src/forms/LocationInfoForm.js

Fixes #1513 
Save location as `{postalCode: ''}` even if skipped.

fix for skipping location

---

f2/src/LandingPage.js
f2/src/locales/en.json
f2/src/locales/fr.json

Fixes #1538(issue)
add app info alert on landing page " this app is best viewed with Chrome or Firefox"
- [x ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)

add app info-best viewed with Chrome or Firefox  on landing page

---

f2/src/summary/EvidenceInfoSummary.js

Fixes #1557
App was only showing files if there was a description. This fixes that.

display files even if no description

---

f2/src/utils/__tests__/getData.test.js
f2/src/utils/getData.js

This renames the files on the server to have the same file extension as the original file. The result will be that (together with #1511) the file attachments on the analyst emails will have correct extensions and be more easily opened.

use extension in file paths

---

f2/src/forms/EvidenceInfoForm.js
f2/src/locales/en.json
f2/src/locales/fr.json

Fixes #1564 (issue)
deleted "English" and "Francais" words in the pop-up message if attached  is larger than 4MB, also corrected the wrong word"buttom" to "button"

delete "English" and "Francais" words in the pop-up message 

---

f2/src/ConfirmationPage.js
f2/src/FinalFeedbackPage.js
f2/src/locales/en.json
f2/src/locales/fr.json

Fixes #1592 
* submitting final feedback (from Cancel or thanks page) leads to finalfeedbackthanks page
* also took out the back button on the finalfeedback page so it'd work with both cancel and thanks
We should probably just make our Back buttons do a `history.back()`. Though then they're exactly the same as pressing the browser back button, so is there a point?

Hookup finalfeedback thanks page

---

f2/src/utils/saveBlob.js

Fixes no real issue.
After reviewing how we described things in the IATO and SA&A and how we're handling malware I don't think we're authorized to be keeping malware files submitted to us in our cloud tenant. Let's follow the baseline (CAFC) route of just junking the malware for now.

Don't save malware!

---

f2/server.js

Fixes #1638 
Use formidable to manually extract the form data rather than all in one go. This lets us extract files with the same name without losing any.

extract data from formidable manually

---

f2/server.js

Yesterday CAFC moved to HTTPS, this broke our allowed origins.

FIX CORS for HTTPS

---

f2/src/forms/EvidenceInfoForm.js

Fixes #1615 
Clear the file input after the alert. Otherwise choosing the same file again doesn't trigger the `onChange` which will show the alert.

clear file input after alert

---

f2/src/LocaleSwitcher.js
f2/src/components/backbutton/index.js

Fixes #1659 
language toggle and go back links were being skipped by keyboard navigation. problem was links without hrefs.
We should probably tweak the PR templates with a line like "if you've changed or added a component ensure that it is keyboard navigatable"

fix keyboard nav

---

f2/server.js

We currently have a counter of about 1 hour between requests. Only after the hour has passed do we redirect a person from CAFC.
This is a problem because we reset the counter every time the web application is visited. An Internal mechanism from Azure seems to be "visiting" our site every 5 minutes and resetting the counter.  This doesn't show up in our App Service HTTPLogs so it must be an internal mechanism.
Because of this we are effectively not taking any redirects.
This PR adds a check for the referrer to verify the traffic is coming from CAFC before incrementing the counter.
How to test:
To test:
Step 1:
Add a fake DNS entry to your hosts. This makes it so a url points to the web server on YOUR computer.
On Mac OS: edit the file /private/etc/hosts
And add the following entry: …

Emergency Fix - Don't count non-CAFC referrals

---

f2/src/ConfirmCancelPage.js

Fixes #1650 (issue)
change "go back" button's height to the same height as "cancel report"… button on confirmCancel page

change "go back" button's height to the same height as "cancel report" button

---

utils/azurescript.sh

The Continuous deployment was not working.  I need to add these IP ranges as specified by MS in order to allow communication from the ACR.  See bit.ly/2xGlegR for details.
Nope
I have tested these lines individually and run them against all RCMP environments successfully.  After doing so for the DEV environment it has fixed the Continuous Deployment issues and builds are getting pushed to the App Service.

Fix for Continuous Deployment

---

f2/package-lock.json
f2/package.json
f2/server.js
f2/src/ConfirmationPage.js
f2/src/utils/getData.js

Flatten report before the app submits it, then unflatten it in the server.
This allows us to submit each piece of data in its own field rather than bundling it all up into one `json` field. Hopefully the WAF will like this more.
[flat](https://www.npmjs.com/package/flat) (currently 1.8M weekly downloads)

Flatten report before submitting

---

f2/src/utils/formatAnalystEmail.js

Fixes #1701 
> We added submissionDate to the report metadata to allow us to search the database for the number of reports submitted already (in case of a reboot). That field isn't needed in the analyst email - we should delete in formatAnalystEmail() right after we copy the data.
> no
> no

remove submissionDate from the analyst email

---

f2/src/components/EditButton/__tests__/EditButton.test.js
f2/src/components/EditButton/index.js

Fixes #1746 
Hide edit buttons on confirmation page if user submits and then navigates back.

hide edit button if form submitted

---

f2/src/locales/en.json
f2/src/locales/fr.json

Fixes #1766
change the "next page" text on the consent page, since now there's the anonymous page there.

update next page text for consent page

---

README.md

Fixes #1702
add info the README about getting the analyst emails yourself

add instructions for getting unencrypted analyst email

---

f2/src/ConfirmationSummary.js
f2/src/forms/WhatWasAffectedForm.js
f2/src/utils/formatAnalystEmail.js

Fixes #1762
We got rid of the `whatWasAffected` `optionOther` field a while ago but didn't take the (now always empty field) out of the report data. This PR removes it everywhere.

remove unused optionOther field

---

f2/src/ConfirmationSummary.js
f2/src/summary/BusinessInfoSummary.js
f2/src/summary/ContactInfoSummary.js
f2/src/summary/DevicesSummary.js
f2/src/summary/EvidenceInfoSummary.js
f2/src/summary/HowDidItStartSummary.js
f2/src/summary/InformationSummary.js
f2/src/summary/LocationInfoSummary.js
f2/src/summary/MoneyLostInfoSummary.js
f2/src/summary/SuspectCluesSummary.js
f2/src/summary/WhatHappenedSummary.js
f2/src/summary/WhatWasAffectedSummary.js

Fixes #1742
> On the confirmationSummaryPage, we used to export EditButton
This component has been moved into the components folder.
We are exporting an alias of EditButton from confirmationSummaryPage to avoid breaking all summary blocks pages.
> no
> no

Import EditButton from components on summary block pages

---

f2/server.js

I was looking at the code and I saw that these URL were still HTTP.  The source site is redirecting to https automatically now, so this PR has little consequence I suppose, but might as well correct it.
Todo: Test the change and make sure the redirect still works?

Change CAFC redirect to https

---

f2/src/ConfirmationPage.js
f2/src/FinalFeedbackPage.js
f2/src/ThankYouPage.js
f2/src/components/EditButton/__tests__/EditButton.test.js
f2/src/components/EditButton/index.js
f2/src/forms/ConfirmationForm.js
f2/src/forms/defaultValues.js
f2/src/utils/state.js

Fixes a bug where second submission (ie trying after a first failure) would always be rejected.
To test locally:
- `npm run prod` and go through app. Submission works.
- Go back with browser back button. Confirmation page knows you've already submitted and has your report id at the bottom.
- Now go forward to the thankyou page and "create a new report". Verify that this still works and you can submit a new report.
- Next go back to the landing page, and stop `server.js` in your terminal. Fill out the report. The submission should fail (since the server isn't running).
- Click "Back to your report" - the confirmation page should have Edit links and a submit button.
- Run `node server.js` in your terminal and wait a few seconds for it to boot.
- Click "Submit report". This time the …

Move submitted and reportId out of formData

---

f2/server.js

> In Node `console.info()` is an alias for `console.log()` and both of these will write to stdout.  When entries from stdout get absorbed into Azure they are recorded as Informational records in Log Analytics. 
> Additionally, `console.warn()` is an alias for `console.error()` and both of these will write to stderr.  When entries from stderr get absorbed into Azure they are recorded as Error records in Log Analytics.
> In this case, I wanted to change this log line from being an Error to being Information.
> In the future we could write to the log analytics workspace API and choose from a number of log categories.  https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#overview

Changing log from error to info

---

f2/src/utils/encryptedEmail.js

Fixes #1910(issue)
when victim input self harm words in the report, the analyst's email will have a
warning message" WARNING: self harm words detected" in subject line for easily tracking

add warning message in email subject if self harm words detected

---

f2/src/utils/formatAnalystEmail.js

Fixes #1855
> The "Report Language" should be displayed "English or French" instead of "en or fr" in analyst mail
> no
>

Should "Report Language" be displayed full word in analyst mail

---

f2/src/forms/PrivacyConsentInfoForm.js

Fixes #1929
> When you click consent on privacy page, go to the next page and then click on go back button. This check on privacy consent is not saved like the info on the other pages are saved.
> no
> no

privacy consent page should be recorded as the other page

---

f2/src/AnonymousPage.js
f2/src/BusinessPage.js
f2/src/ContactInfoPage.js
f2/src/DevicesPage.js
f2/src/EvidencePage.js
f2/src/Home.js
f2/src/HowDidItStartPage.js
f2/src/InformationPage.js
f2/src/LocationAnonymousPage.js
f2/src/LocationPage.js
f2/src/MoneyLostPage.js
f2/src/WhatHappenedPage.js
f2/src/WhatWasAffected.js

This PR  redirect the user back to the consent page if user cancel a report and then use back button  go back to the report flow.
Fixes #1934 #1925(issue)
before this PR : if user cancel a report and then use back button , user will go back to the report flow. This PR redirect the user back to the consent page by using  route component,  Also, delete unneeded code, make code easier to maintenance. 
No
No

redirect user to consent page if user cancel a report in half way

---

utils/azurescript.sh

Policy dictates that we should only allow secure FTP communication.  We will take it a step further and disable it entirely.  This has already been done to our current active environments.

Disable FTP(S)

---

f2/src/AnonymousPage.js
f2/src/utils/state.js

Fixes #1954
> Part one: If the user cancels at summary page and use the back arrow key to go back to the previous pages, it will take the user to your privacy page. ---> That's good
Part two: From the privacy page, the user clicks on consent and press continue to go to Report Anonymously page. AT this page, the user clicks on Continue button to go to the next page and here is the issue
Actual Result: The next page is "Review your report" page
Expected Result: The next page should be "How did the incident start?" page
> no
> no

form flow fix when cancelled at summary page

---

f2/server.js

The Winston-Express config was mistakenly colorizing the records.  There was a setting which was overriding our desire to not colourize.
> I removed the line and tested the updated code and I can see that the colourizing characters in question have been removed.
> Take master branch and Run the server locally and visit localhost:3000.  Then look at the server logging, and after formatting the JSON logging you will see that the "level" attribute is displayed with extra colorizing characters.
> Then, take this branch and do the same test and you will see that those characters have been removed.

Stop Colorizing WinstonExpress

---

f2/src/CancelPage.js

Fixes #1986
> To be consistent, when the user clicks on any links in the cancellation page, a new page should be opened. Currently, it overrides the current page
Additional quote from Hong "I think we are good with Tell us more and Create a new report. When the user clicks on "Create a new report", it will use the same tab. In this way, it will not confuse the users. "Tell us more" will use the same tab as well but it will be bring back the thank you page when the user hit the submit button on the feedback. I think it is good too"
> no
> no

Click on any link in cancellation page should be open a new page

---

f2/src/utils/formatAnalystEmail.js

Fixes #2032
> If a user enters a postal code in correct format (B1B1B1 B2B2B2) but not actually in the Canadian Postal Code lookup, this will produce an error when creating the e-mail for the analyst:
ERROR in formatAnalystEmail (report NCFRS-p7n6cwadgea): TypeError: Cannot read property 'city' of undefined
The solution:
For a hot fix: We should initialize to blank strings if the postal code lookup comes back with nothing
However long term: Validate that the postal code actually exists and display a message to user.
> Give details

If a user enters an invalid postal code, the report to the analyst is malformed. 

---

f2/src/utils/acceptableFiles.js

Fixes #2019( issue)
The application currently has multiple functions that serve the same purpose. Issues like this make the app harder to maintain and causes unexpected outcomes. 
The PR  refactor the project to ensure only getFileExtension function in use to extract the extension of a file. 

only USE getFileExtension function in the app. remove other functions to extract the extension of a file

---

f2/src/locales/en.json
f2/src/locales/fr.json
f2/src/utils/formatAnalystEmail.js

Fixes #2125
> According to the questions asked on the current website, the new analyst reports should indicate "Information requested by the suspect" and "Information obtained by the suspect".
> no
> no

Analyst Report Suspect Header Error

---

f2/src/forms/WhoAreYouReportForForm.js
f2/src/summary/WhoAreYouReportForSummary.js

Fixes #2162 
> Added code of marking ids for lingui in WhoAreYouReportForForm.js and WhoAreYouReportForSummary.js to fix the problem that message strings in en.json/fr.json are removed by pre-commit hook
> Give details

Adding code to mark ids for Lingui

---

f2/src/locales/en.json
f2/src/locales/fr.json
f2/src/utils/formatAnalystEmail.js

Fixes #2128(issue)
d delete the fields since it already added to analyst email template to avoid the field show up at the button of the analyst email. This PR also reorder the the en.json and fr.json. the hook has formatted the code so it show adding new line in FormatAnalystEmail.js .
no 
> Give details

delete field since it already added to analyst email template

---

f2/src/forms/EvidenceInfoForm.js
f2/src/locales/en.json
f2/src/locales/fr.json
f2/src/utils/formatAnalystEmail.js

Fixes #2225 
In the file upload/scan section, there are 2 places still in English while user wrote French report.
One is "scan clean", the other one is "'Image classification:', 'Could not scan content'"
In the analyst report part and associated language definition and evidenceForm
No
> Give details
- [ X] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)

Extra English in final analyst French Report

---

f2/src/locales/fr.json

Fixes #2313 
> "File Upload Error" should be displayed as French if the language is set to French
> Give details

"File Upload Error" should be displayed as French if the language is set to French

---

f2/src/utils/formatAnalystEmail.js

Fixes #2166 
This is to fix the issue of extra spaces were injected to the type in of "other" in financial loss section, and forcefully turned to lower case when user type in any (like "BBBBB") in other, the report showed "b b b b b "
It was in other branch, however due to unexpected content shows up during rebase stage, create this branch to have a clean push.
What happened? | I WAS ASKED TO PAY $5000
-- | --
Amount of money asked for by suspect | 5555
Information asked for by suspect | credit card, dob, sin, CCCCCCCCCC, home address ===> "CCCCCC" 100% reserved
Amount of money stolen by suspect | 1111
Information obtained by suspect | credit card, dob, home address, sin, DDDDDDDDDDDD ==> 100% reserved
Suspect name | CRA
-- | --
Suspect email | we@gmail.com
Suspect phone number | (613) …

Copy fix to this branch for extra space issue PR2166

---

f2/src/utils/scanFiles.js

Fixes #(issue)
Backfills hotfix to save failed to scan files into master from staging
Backfills hotfix to save failed to scan files into master from staging
No
> Give details
Needs to enable storage at azure app settings

backfill saving failed to scan files

---

f2/src/locales/fr.json

Typo fix: "Confidentialité de la déclaration" -> "Déclaration de confidentialité"
Looks like it worked its way in with PR #2155. The corrected spelling uses the spelling of the phrase on the same page.
n/a
n/a

Fix typo in privacy and consent (FR)

---

f2/src/forms/SuspectCluesForm.js

Fixes #2391(issue)
fixe the  error:  (Missing form label) when runs WAVE on Add suspect clues page
> Give details
- [x ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)

add label for the form control in suspect clue page

---

f2/cypress/integration/common/home.js
f2/cypress/integration/generate_fyi_report_fr.feature
f2/src/locales/fr.json

Fixes #2438 (issue)
It was found in the FYI button title change, French translation got error due to copy/paste from TEAM
It is now
Submit a general tip - Soumettre un renseignemen
It should be
Submit a general tip - Soumettre un renseignement
Cypress is also updated
> Give details
- [ X] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)

Fix French translation error in FYI button title change

---

f2/src/pdf/InformationView.js

Fixes #2394 (issue)
This is to fix wrong title at Personal Information in PDF
> Give details
- [X ] I have looked at my code on GitHub and it all looks good (ex: no random commented out code or console.logs)

Solve wrong personal ino title in PDF
